name: metronome
description: "A Flutter metronome app with simple and complex (track) modes."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  provider: ^6.1.0
  file_saver: ^0.2.12
  petitparser: ^6.0.2
  flutter_code_editor: ^0.3.5
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  qr_flutter: ^4.1.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
